GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Be happy"
}


###

DELETE http://localhost:3001/todo/delete/64488f45cfc7f48239b20ac1


###

GET HTTP/1.1 http://localhost:3001/todo/complete/6449d641136097fe9094c213